name: Deploy Frontend

on:
  push:
    branches:
      - master



jobs:
  build:
    runs-on: [react]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and build frontend
        run: |
          npm install
          npm run build

      - name: Deploy to nginx
        run: |
          sudo cp -r dist/* /var/www/html/
